# Generated by Django 5.0.4 on 2024-06-01 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Manage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("案件名", models.CharField(max_length=100)),
                (
                    "プラン名",
                    models.CharField(
                        choices=[
                            ("plan01", "アドバンスドプラン"),
                            ("plan02", "レギュラープラン"),
                            ("plan03", "スマートプラン"),
                            ("plan04", "For採用"),
                            ("plan05", "ダイレクトセールス"),
                            ("plan06", "社内案件"),
                            ("plan07", "有償メンテナンス"),
                            ("plan08", "LP"),
                            ("plan09", "直案件"),
                            ("plan10", "名刺"),
                            ("plan11", "封筒"),
                            ("plan12", "ロゴ"),
                            ("plan13", "WEBサイト"),
                            ("plan14", "チラシ"),
                            ("plan99", "その他"),
                        ],
                        default="plan01",
                        max_length=100,
                    ),
                ),
                (
                    "デザイナー名",
                    models.CharField(
                        choices=[
                            ("designer01", "菊田"),
                            ("designer02", "魚戸"),
                            ("designer03", "後"),
                            ("designer04", "和田"),
                            ("designer05", "福原"),
                            ("designer99", "その他"),
                        ],
                        default="designer01",
                        max_length=100,
                    ),
                ),
                (
                    "コーダー名",
                    models.CharField(
                        choices=[
                            ("coder01", "ラジ"),
                            ("coder02", "久保木"),
                            ("coder03", "菅野"),
                            ("coder04", "小濱"),
                            ("coder05", "稲野"),
                            ("coder06", "青木"),
                            ("coder99", "その他"),
                        ],
                        default="coder01",
                        max_length=100,
                    ),
                ),
                (
                    "ディレクター名",
                    models.CharField(
                        choices=[
                            ("director01", "木下"),
                            ("director02", "永見"),
                            ("director03", "春木"),
                            ("director04", "野本"),
                            ("director05", "中吉"),
                            ("director98", "営業"),
                            ("director99", "その他"),
                        ],
                        default="director01",
                        max_length=100,
                    ),
                ),
                ("納品月", models.CharField(default="", max_length=7)),
                (
                    "備考",
                    models.TextField(blank=True, default="", max_length=999, null=True),
                ),
                (
                    "ユーザー名",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
