# Generated by Django 5.0.4 on 2024-06-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manage",
            name="終了日",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="manage",
            name="開始日",
            field=models.CharField(default="", max_length=10),
        ),
    ]
