# Generated by Django 5.0.6 on 2024-06-01 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_app", "0002_manage_終了日_manage_開始日"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manage",
            name="納品月",
            field=models.CharField(default="", help_text="例: 2023-06", max_length=7),
        ),
        migrations.AlterField(
            model_name="manage",
            name="終了日",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="manage",
            name="開始日",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
